config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    member do
      post :add_to_friend
      post :create_post
      delete :delete_friend
      # /users/:id/add_to_friend
      # /users/2/add_to_friend
      # /users/2/create_post
    end
  end
  
  resources :groups do
    member do
      post :create_post
      post :subscribe
      delete :unsubscribe
      # /groups/:id/create_post
    end
  end

  resources :conversations, only: [:index, :create, :new] do
    resources :messages, only: [:index, :new, :create]
  end

  resources :friend_requests, only: [:index] do
    member do
      put :approve
      put :decline
    end
  end

  resources :news, only: [:index]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_groups_on_user_id  (user_id)
#

# groups_users
# user_id
# group_id

class Group < ApplicationRecord
  belongs_to :author, foreign_key: :user_id, class_name: 'User'
  has_and_belongs_to_many :users
  validates :title, format: { with: /\A[A-zА-я \d.!?]+\z/, 
                              message: 'допустимы только буквы' }
  has_many :albums, as: :albumable
  has_many :likes, as: :likeable
  has_many :posts, as: :postable

  scope :without_user, lambda { |u| where("#{quoted_table_name}.id NOT IN (SELECT groups_users.group_id FROM groups_users WHERE groups_users.user_id = ?)", u.id) }

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :check_user!
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def index
    @authored_groups = current_user.authored_groups
    # @new_groups = Group.includes(:users).where('(groups.user_id != ?) AND (SELECT users.id != ?)', current_user.id, current_user.id).references(:users)
    @new_groups = Group.without_user(current_user).where.not(groups: { author: current_user })
    # gr = Group.joins("join groups_users on users.id = groups_users.user_id").where(["groups_users.user_id != ?", current_user.id])
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.author = current_user
    if @group.save
      @group.users << current_user if !@group.users.include? current_user
      flash[:success] = 'Группа создана'
      redirect_to @group
    else
      flash[:error] = 'Ошибка'
      redirect_to groups_path
    end
  end

  def edit
    @group = Group.find(params[:id])
    redirect_to group_path(@group) if @group.author != current_user
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.author == current_user
      if @group.destroy
        flash[:success] = "Группа удалена"
        redirect_to groups_path
      else
        flash[:error] = "Ошибка"
        redirect_to edit_group_path(@group)
      end
    else
      flash[:error] = "Нет прав"
      redirect_to edit_group_path(@group)
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.author == current_user
      @group.assign_attributes(group_params)
      if @group.save
        flash[:success] = "Изменения сохранены."
        render :show
      else
        render :show
      end
    else
      flash[:error] = 'Вы не можете быть редактором'
      redirect_to group_path(@group)
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def subscribe
    @group = Group.find(params[:id])
    @group.users << current_user if !@group.users.include? current_user
    flash[:success] = "Вы подписаны на #{@group.title}"
    redirect_to @group
  end

  def unsubscribe
    @group = Group.find(params[:id])
    if @group.users.include? current_user
      if @group.users.delete(current_user)
        flash[:success] = "Вы отписались"
        redirect_to groups_path
      else
        flash[:error] = "Ошибка"
        redirect_to edit_group_path(@group)
      end
    else
      flash[:error] = "Ошибка"
      redirect_to edit_group_path(@group)
    end
  end

  def create_post
    @group = Group.find(params[:id])
    @post = @group.posts.new
    @post.assign_attributes(post_params)
    @post.author = current_user
    if @post.save
      flash[:success] = 'Запись создана'
      redirect_to @group
    else
      flash[:error] = 'Ошибка'
      redirect_to @group
    end
  end

  def not_found
    render 'shared/not_found'
  end

  private
  def post_params
    params.require(:post).permit(:body)
  end

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h1>Редактирование группы</h1>

<%= form_for (@group) do |f| %>
  <div class="form-group col-sm-12">
    <div class="col-sm-2">
      <%= f.label :title %>
    </div>
    <div class="col-sm-12">
      <div class="col-sm-4">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <div class="col-sm-2">
      <%= f.label :description %>
    </div>
    <div class="col-sm-12">
      <div class="col-sm-4">
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="col-sm-12 form-group">
    <div class="col-sm-4">
      <%= f.submit t(:save), class: "btn btn-primary" %>
    </div>
  </div>
  
    
<% end %>
<div class="col-sm-12 form-group">
  <div class="col-sm-4">
    <%= link_to 'Удалить группу', @group, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>

app/views/groups/index.html.erb
<div>
  <div>
    <%= link_to 'Создать группу', new_group_path, class: 'btn btn-default'%>
  </div>
  Список групп
</div>
<div class="col-sm-12">
  Вы автор:
  <div>
    <% @authored_groups.each do |group| %>
      <%= link_to group.title, group %></br>
      <%= group.description %></br></br>
    <% end %>
  </div>
</div>

<div class="col-sm-12">
  Предложения:
</div>
<div class="col-sm-12">
  <% @new_groups.each do |group| %>
    <%= link_to group.title, group %></br>
    <%= group.description %></br></br>
  <% end %>
</div>

<div class="col-sm-12">
    Ваши группы:
</div>
<div class="col-sm-12">
  <% @groups.each do |group| %>
    <%= link_to group.title, group %></br>
    <%= group.description %></br></br>
  <% end %>
</div>

app/views/groups/new.html.erb
<%= form_for (@group) do |f| %>
  <div class="form-group">
    <div class="form-group col-sm-12">
      <%= f.label :title %>
    </div>
    <div class=col-sm-4>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
    
    <div class="form-group col-sm-12">
      <%= f.label :description %>
    </div>
    <div class=col-sm-4>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div>
      <%= f.submit t(:create_group), class: "btn btn-primary" %>
    </div>

<% end %>

app/views/groups/show.html.erb
<%= @group.title %></br>
<%= @group.description %>

<div>
  <% if @group.author == current_user %>
    <div class="form-group">
      <%= link_to 'Редактировать группу', edit_group_path(@group), class: 'btn, btn-primary' %>  
    </div>
  <% end %>
  <% if @group.users.include? current_user%>
    <% if @group.author != current_user %>
      <div>
        <%= link_to 'Отписаться ', unsubscribe_group_path(@group), method: :delete, class: 'btn, btn-danger' %>
      </div>
    <% end %>
  <% end %>
  <% if !@group.users.include? current_user %>
    <% if @group.author != current_user %>
      <div>
        <%= link_to 'Подписаться', subscribe_group_path(@group), method: :post, class: 'btn, btn-success'  %>  
      </div>
    <% end %>
  <% end %>
  <%= form_for :post, url: create_post_group_path(@group), method: :post do |f| %>
  <div class="field">
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div>
      <%= f.submit t(:save), class: "btn btn-primary" %>
    </div>
    <% end %>

    <% if @post.present? %>
      <%= @post.errors.full_messages  %>
    <% end %>

    <% @group.posts.each do |post| %>
      <%# post.group.title %>
      <%= post.author.name %></br>
      <%= post.body %></br>
      <%= post.likes.count %></br>
      <%= post.photos.count %></br></br>
  <% end %>
  </div>

</div>