config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    member do
      post :add_to_friend
      post :create_post
      delete :delete_friend
      # /users/:id/add_to_friend
      # /users/2/add_to_friend
      # /users/2/create_post
    end
  end
  
  resources :groups do
    member do
      post :create_post
      post :subscribe
      delete :unsubscribe
      # /groups/:id/create_post
    end
  end

  resources :conversations, only: [:index, :create, :new] do
    resources :messages, only: [:index, :new, :create]
  end

  resources :friend_requests, only: [:index] do
    member do
      put :approve
      put :decline
    end
  end

  resources :news, only: [:index]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  surname                :string
#  age                    :integer
#  male                   :boolean
#  country                :string
#  city                   :string
#  description            :text
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  lat                    :decimal(10, 6)
#  lng                    :decimal(10, 6)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friend_requests, foreign_key: :recipient_id
  has_many :authored_groups, foreign_key: :user_id, class_name: 'Group'
  has_and_belongs_to_many :groups
  has_many :albums, as: :albumable
  has_many :posts, as: :postable
  has_many :likes, as: :likeable
  has_and_belongs_to_many :hobbies
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  MALE_SET = [['Мужской', 1], ['Женский', 0], ['Не указан', 'nil']].freeze

  # validates :name, length: { in: 2..15}, format: { with: /\A[A-zА-я]+\z/,
  #                          message: 'допустимы только буквы' }
  # validates :surname, length: { in: 2..20},  format: { with: /\A[A-zА-я]+\z/, 
  #                             message: 'допустимы только буквы' }
  # validates :age, numericality: true
  # validates :country, format: { with: /\A[A-zА-я]+\z/, 
  #                             message: 'допустимы только буквы' }
  # validates :city, format: { with: /\A[A-zА-я]+\z/, 
  #                          message: 'допустимы только буквы' }
  def conversations
    Conversation.where('sender_id = ? OR recipient_id = ?', id, id)
  end

  def friends
    users_ids = FriendRequest.where('(sender_id = ? OR recipient_id = ?) AND approved = ?', id, id, true).pluck(:sender_id, :recipient_id)
    users_ids = users_ids.flatten.uniq - [id]

    User.where(id: users_ids)
  end

  def remove_friend(user)
    fr = friend_requests.where(
      '(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)', id, user.id, user.id, id
    )

    fr.destroy_all
  end

  # def nearby_people
  #   User.select('*', "(acos(sin(#{lat}) * sin(users.lat) + cos(#{lat}) * cos(users.lat) * cos(users.lng - (#{lng}))) * 6371) as distance").order('distance ASC')
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user!
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def show
    @user = User.find(params[:id])
  end

  def edit
    redirect_to edit_user_path(current_user) if params[:id] != current_user.id.to_s
    @user = current_user
  end

  def update
    @user = current_user
    @user.assign_attributes(user_params)
    @user.male = nil if user_params[:male] == 'nil'
    if @user.save
      flash[:success] = "Изменения сохранены."
      render :edit
    else
      render :edit
    end
  end

  def create_post
    @user = User.find(params[:id])
    @post = @user.posts.new
    @post.assign_attributes(post_params)
    @post.author = current_user
    if @post.save
      flash[:success] = 'Запись создана'
      redirect_to @user
    else
      flash[:error] = 'Ошибка'
      redirect_to @user
    end
  end

  def not_found
    render 'not_found'
  end

  def add_to_friend
    @user = User.find(params[:id]) 
    if !current_user.friends.include? @user
      if @user.friend_requests.find_by(sender: current_user).present?
        flash[:success] = "Заявка уже отправлена"
        redirect_to @user
      else
        if @user.friend_requests.create(sender: current_user)
          flash[:success] = "Дружба создана"
          redirect_to @user
        else
          flash[:error] = "Дружба не создана"
          redirect_to @user
        end
      end
    else
      flash[:error] = "Уже в друзьях"
      redirect_to @user
    end
  end

  def delete_friend
    @user = User.find(params[:id])
    if current_user.remove_friend(@user)
      flash[:success] = "Дружба расторгнута"
      redirect_to :back
    else
      flash[:error] = "Не удалось удалить"
      redirect_to :back
    end
  end

  protected

  def check_user!
    redirect_to root_path unless user_signed_in?
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :age, :male, :city, :country, :description, :avatar)
  end

  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="row">
  <%= link_to user do %>
    <div class="col-sm-12 col-md-2">
      <div class="friends-avatar img-circle" style="background-image: url(<%= user.avatar.url(:thumb) %>)"></div>
    </div>
  <% end %>

  <div class="col-sm-12 col-md-10">
    <%= link_to user do %>
      <h5><%= [user.name, user.surname].join(' ') %></h5>
    <% end %>
    <% if yield.present? %>
      <%= yield %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Редактирование страницы</h1>


<% if @user.errors.present? %>
  У юзера есть ошибки:<br>
  <% @user.errors.full_messages.each do |m| %> 
    <%= m %><br>
  <% end %>
<% end %>
<div class="form-horizontal">
  <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "col-sm-2" %>
      <div class="col-sm-10">
        <div class="col-sm-4">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :surname, class: "col-sm-2" %>
      <div class="col-sm-10">
        <div class="col-sm-4">
          <%= f.text_field :surname, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :age, class: "col-sm-2" %>
      <div class="col-sm-10">
        <div class="col-sm-4">
          <%= f.number_field :age, in: 1..100, step: 1, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :male, class: "col-sm-2" %>
      <div class="col-sm-10">
        <div class="col-sm-4">
          <%= f.select :male, options_for_select(User::MALE_SET, (@user.male.nil? ? 'nil' : (@user.male ? 1 : 0)) ), class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :country, class: "col-sm-2" %>
      <div class="col-sm-10">
        <div class="col-sm-4">
          <%= f.text_field :country, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :city, class: "col-sm-2" %>
      <div class="col-sm-10">
        <div class="col-sm-4">
          <%= f.text_field :city, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-sm-2" %>
      <div class="col-sm-10">
        <div class="col-sm-4">
          <%= f.text_area :description, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :avatar, class: "col-sm-2"%>
      <div class="col-sm-10">
    <%= image_tag @user.avatar.url(:thumb) %></br>
    <%= f.file_field :avatar %>
      </div>
    </div>


    <div class="actions">
      <%= f.submit "Отправить", class: 'btn btn-success' %>
      <%= link_to "Назад", user_path(@user) %>
    </div>
  <% end %>
</div>

app/views/users/not_found.html.erb
NOT FOUND PAGE

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <h2><%= [@user.name, @user.surname].join(' ') %></h2>
    <div>
      <%= image_tag @user.avatar.url(:medium), class: 'img-rounded' %>
    </div>
    <dl>
      <dt>Возраст:</dt>
      <dd><%= @user.age %></dd>
      <dt>Пол:</dt>
      <dd><%= @user.male.nil? ? 'Не указан' : (@user.male ? 'Мужчина' : 'Женщина') %></dd>
      <dt>Страна:</dt>
      <dd><%= @user.country %></dd>
      <dt>Город:</dt>
      <dd><%= @user.city %></dd>
    </dl>
  </div>
  <div class="col-xs-6">
    <div>
      <h3>О себе:</h3>
    </div>
    <div>
      <p><%= @user.description %></p>
    </div>
  </div>
</div>

<div>
  <% if @user != current_user %>
    <% if !current_user.friends.include? @user %>
      <% if @user.friend_requests.find_by(sender: current_user).present? %>
        Заявка уже отправлена
      <% else %>
        <%= form_for :user, url: add_to_friend_user_path(@user.id), method: :post do |f| %>
          <%= f.submit t(:add_to_friends) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <% if current_user.friends.include? @user%>
    <%= @user.name %> ваш друг
  <% end %>
</div>
<h3>Записи на стене:</h3>
<% @user.posts.each do |post| %>
  <div class="row">
    <div class="col-xs-12">
      <%= post.author.name %></br>
      <%= post.body %></br>
      <%= post.likes.count %></br>
      <%= post.photos.count %></br></br>
      ...
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-8">
    <%= form_for :post, url: create_post_user_path(@user), method: :post do |f| %>
      <div class="form-group">
        <%= f.text_area :body, class: "form-control", style: 'max-width: 100%; max-height: 200px; min-height: 100px;' %>
      </div>
      <div>
        <%= f.submit t(:save), class: "btn btn-default" %>
      </div>
    <% end %>

    <% if @post.present? %>
      <%= @post.errors.full_messages  %>
    <% end %>
  </div>

  <div class="col-xs-4">
  </div>

</div>