config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    member do
      post :add_to_friend
      post :create_post
      delete :delete_friend
      # /users/:id/add_to_friend
      # /users/2/add_to_friend
      # /users/2/create_post
    end
  end
  
  resources :groups do
    member do
      post :create_post
      post :subscribe
      delete :unsubscribe
      # /groups/:id/create_post
    end
  end

  resources :conversations, only: [:index, :create, :new] do
    resources :messages, only: [:index, :new, :create]
  end

  resources :friend_requests, only: [:index] do
    member do
      put :approve
      put :decline
    end
  end

  resources :news, only: [:index]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/shared/_footer.html.erb
<center>
Год
<%= Time.now.year %>  
</center>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SOCIAL NETWORK', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li>
            <%= link_to('Выход', destroy_user_session_path, :method => :delete) %> 
          </li>
        <% else %>
          <li>
            <%= link_to 'Регистрация', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Вход', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <li role="presentation" class="<%= (controller?(:users) && action?(:show) ? 'active' : '') %>">
    <%= link_to 'Страница', current_user %>
  </li>
  <li role="presentation" class="<%= (controller?(:friend_requests) && action?(:index) ? 'active' : '') %>">
    <%= link_to 'Друзья', friend_requests_path %>
  </li>
  <li role="presentation" class="<%= (controller?(:news) && action?(:index) ? 'active' : '') %>">
    <%= link_to 'Новости', news_index_path %>
  </li>
  <li role="presentation" class="<%= (controller?(:groups) && action?(:index) ? 'active' : '') %>">
  <%= link_to 'Группы', groups_path %>
  </li>
  <li role="presentation">
    <a href="">Фотографии</a>
  </li>
  <li role="presentation" class="<%= (controller?(:conversations) && action?(:index) ? 'active' : '') %>">
    <%= link_to 'Сообщения', conversations_path %>
  </li>
  <li role="presentation" class="<%= (controller?(:users) && action?(:edit) ? 'active' : '') %>">
    <%= link_to 'Настройки', edit_user_path(current_user) %>
  </li>
</ul>

app/views/shared/not_found.html.erb
NOT FOUND PAGE