config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    member do
      post :add_to_friend
      post :create_post
      delete :delete_friend
      # /users/:id/add_to_friend
      # /users/2/add_to_friend
      # /users/2/create_post
    end
  end
  
  resources :groups do
    member do
      post :create_post
      post :subscribe
      delete :unsubscribe
      # /groups/:id/create_post
    end
  end

  resources :conversations, only: [:index, :create, :new] do
    resources :messages, only: [:index, :new, :create]
  end

  resources :friend_requests, only: [:index] do
    member do
      put :approve
      put :decline
    end
  end

  resources :news, only: [:index]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/friend_request.rb
# == Schema Information
#
# Table name: friend_requests
#
#  id           :integer          not null, primary key
#  sender_id    :integer
#  recipient_id :integer
#  approved     :boolean
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_friend_requests_on_recipient_id                (recipient_id)
#  index_friend_requests_on_sender_id                   (sender_id)
#  index_friend_requests_on_sender_id_and_recipient_id  (sender_id,recipient_id) UNIQUE
#

class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :check_user!

  def index
    @friend_requests = current_user.friend_requests.where(approved: nil).limit(3)
    @friends = current_user.friends.page(params[:page]).per(20)
  end

  def approve
    fr = FriendRequest.find(params[:id])
    fr.approved = true
    if fr.save
      flash[:success] = 'Успех'
      redirect_to :friend_requests
    else
      flash[:success] = 'Ошибка'
      redirect_to :friend_requests
    end
  end

  def decline
    fr = FriendRequest.find(params[:id])
    fr.approved = false
    if fr.save
      flash[:success] = 'Успех'
      redirect_to :friend_requests
    else
      flash[:success] = 'Ошибка'
      redirect_to :friend_requests
    end
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/index.html.erb
<% if @friend_requests.count != 0 %>
  <h3>Новые заявки в друзья</h3>
  <% @friend_requests.each do |fr| %>
    <% user = fr.sender %>

    <%= render user do %>

      <ul class="list-unstyled button-list">
        <li>
          <%= link_to 'Добавить', approve_friend_request_path(fr), method: :put, class: 'btn btn-default' %>
        </li>
        <li>
          <%= link_to 'Отклонить', decline_friend_request_path(fr), method: :put, class: 'btn btn-default' %>
        </li>
      </ul>

    <% end %>

  <% end %>
<% end %>

<% if @friends.count != 0 %>
  <h3>Друзья:</h3>
  <% @friends.each do |user| %>
    <%= render user %>
    <%= link_to 'Удалить из друзей', delete_friend_user_path(user), method: :delete, class: 'btn btn-default' %>
    <%# TODO: remove from friends %>
  <% end %>
<% else %>
  <div>У вас еще нет друзей! :(</div>
<% end %>